# Generated by Django 5.1.7 on 2025-03-28 05:29

import threads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=threads.models.get_file_path),
        ),
    ]
